package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const (
	StatusWrongNumberOfArguments = 1
	StatusKnavCommandNoFound     = 2
	StatusAbortedOperation       = 3
	StatusKubectlCommandFailed   = 4
)

func main() {
	var trg Target

	// Handle completion-related subcommands before any config / fzf logic.
	// These must be fast, side-effect-free, and never invoke the target picker.
	if len(os.Args) >= 2 {
		switch os.Args[1] {
		case "__complete", "__completeNoDesc":
			runKubectlComplete(os.Args[1], os.Args[2:])
			return
		case "completion":
			runCompletionScript(os.Args[2:])
			return
		}
	}

	err := CreateDefaultConfigIfEmpty()
	if err != nil {
		panic(err)
	}

	cfg, err := LoadConfig()
	if err != nil {
		cfg = DefaultConfig()
	}

	if len(os.Args) == 1 {
		prev := cfg.Current
		trg, err = cfg.PickTarget()
		if err != nil {
			panic(err)
		}
		if trg.Name != prev {
			if err := runInitScript(trg); err != nil {
				fmt.Fprintf(os.Stderr, "init script failed: %v\n", err)
				os.Exit(1)
			}
		}
		return
	} else {
		trg, err = cfg.CurrentTarget()
		if err != nil {
			panic(err)
		}
	}

	args := os.Args[0:]

	knavIndex := -1
	for i, arg := range args {
		if arg == "knav" {
			knavIndex = i
			break
		}
	}

	if knavIndex == -1 {
		fmt.Println("Error: 'knav' not found in arguments")
		os.Exit(StatusKnavCommandNoFound)
	}

	actionIndex := knavIndex + 1
	action := args[actionIndex]
	err = IsPermitted(trg, action)
	if err != nil {
		fmt.Println(err)
		os.Exit(StatusAbortedOperation)
	}

	kubectlArgs := args[knavIndex+1:]
	cmd := exec.Command("kubectl", kubectlArgs...)
	env := os.Environ()
	kPath, err := expandPath(trg.KubeconfigPath)
	if err != nil {
		panic(err)
	}
	env = append(env, "KUBECONFIG="+kPath)
	for _, e := range trg.Envs {
		if e.Name == "" {
			continue
		}
		env = append(env, e.Name+"="+e.Value)
	}
	cmd.Env = env
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	err = cmd.Run()
	if err != nil {
		fmt.Println(err)
		os.Exit(StatusKubectlCommandFailed)
	}
}

func expandPath(p string) (string, error) {
	if strings.HasPrefix(p, "~") {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}
		p = filepath.Join(home, p[1:])
	}
	return filepath.Abs(p)
}

func runInitScript(trg Target) error {
	for _, command := range trg.InitScript {
		for {
			cmd := exec.Command("sh", "-c", command)
			cmd.Stdout = os.Stdout
			cmd.Stderr = os.Stderr
			cmd.Stdin = os.Stdin
			err := cmd.Run()
			if err == nil {
				break
			}

			fmt.Printf("\nInit script failed:\n%s\n\n", command)

			fmt.Print("Retry or close window? [r/C]: ")

			var answer string
			fmt.Scanln(&answer)

			if strings.EqualFold(answer, "r") {
				continue
			}

			return fmt.Errorf("command %q failed: %w", command, err)
		}
	}

	return nil
}

// runKubectlComplete forwards the cobra `__complete` / `__completeNoDesc`
// protocol to kubectl. The completion script generated by `knav completion zsh`
// invokes `knav __complete ...` at tab time; we proxy that to kubectl with the
// current target's KUBECONFIG/envs applied, so dynamic completions (pod names,
// namespaces, contexts, ...) come from the cluster the user is actually
// pointed at.
func runKubectlComplete(directive string, args []string) {
	env := os.Environ()

	if cfg, err := LoadConfig(); err == nil {
		if trg, err := cfg.CurrentTarget(); err == nil {
			if kPath, err := expandPath(trg.KubeconfigPath); err == nil {
				env = append(env, "KUBECONFIG="+kPath)
			}
			for _, e := range trg.Envs {
				if e.Name == "" {
					continue
				}
				env = append(env, e.Name+"="+e.Value)
			}
		}
	}

	cmd := exec.Command("kubectl", append([]string{directive}, args...)...)
	cmd.Env = env
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	if err := cmd.Run(); err != nil {
		// kubectl's completion protocol uses exit codes to signal directives;
		// pass them through verbatim.
		if exitErr, ok := err.(*exec.ExitError); ok {
			os.Exit(exitErr.ExitCode())
		}
		os.Exit(1)
	}
}

// runCompletionScript emits kubectl's own completion script with `kubectl`
// rewritten to `knav`. The rewritten script will invoke `knav __complete ...`
// for dynamic completions, which runKubectlComplete proxies back to kubectl.
func runCompletionScript(args []string) {
	if len(args) == 0 {
		fmt.Fprintln(os.Stderr, "usage: knav completion zsh")
		os.Exit(StatusWrongNumberOfArguments)
	}
	shell := args[0]
	switch shell {
	case "zsh":
		// generate, then rewrite. Simple textual replacement is safe here
		// because kubectl's completion script uses the literal token `kubectl`
		// for both the command name and its internal `_kubectl` function.
	default:
		fmt.Fprintf(os.Stderr, "knav completion: only zsh is supported (got %q)\n", shell)
		os.Exit(StatusWrongNumberOfArguments)
	}

	out, err := exec.Command("kubectl", "completion", shell).Output()
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to obtain kubectl completion script: %v\n", err)
		os.Exit(StatusKubectlCommandFailed)
	}

	rewritten := strings.ReplaceAll(string(out), "kubectl", "knav")
	fmt.Print(rewritten)
}
